package com.example.spring_cinema.movies;
// if the terminal signals an error with the URL, check that the application.properties class is populated with the spring start code. Also, change line 1's last /value if needed to the name that you added to the movieController class' @request mapping property so that it matches e.g. /movies in this instance.
import jakarta.persistence.*;

// to create database:
@Entity                     //this turns the class into a database - convention states that table names be plural. The following two annotations create the database table.
@Table(name = "movies")     //creating database table:
public class Movie {
    @Id                      // can't be changed/edited in database. This @ makes the following property a primary key (PK) constraint.
    @GeneratedValue(strategy = GenerationType.IDENTITY) //@flags to SQL that this column's value is set/generated by SQL. The generation-type in brackets sets an auto-incrementing style of value generation (e.g. 1,2,3,4,5,6 with each row entered into table); to create SQL tables from properties as follows:
    private long id;
    @Column(name = "title")
    private String title;           //could also be a VARCHAR data type (for reading in SQL)
    @Column(name = "rating")
    private int rating;
    @Column (name = "duration")
    private int duration;

    //constructing movie object from above-named properties. {i.e. also without ID bc this is hard-set by setter method in postgres.
    public Movie(String title, int rating, int duration){
        this.title = title;
        this.rating = rating;
        this.duration = duration;
    }

    //default constructor:          //though not needed here?
    public Movie(){
    }

    // getters and setters for other classes to access movie (i.e. this class') properties:
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }
}
